version: '3.8'

services:
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always

  backend:
    build:
      context: ./backend
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./backend:/app"
      - gem_data:/usr/local/bundle
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "8000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - "./frontend:/app"
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run serve
    depends_on:
      - backend

volumes:
  postgres_data:
  gem_data:
  node_modules:
